# Generated by Django 4.2.30 on 2026-06-17 00:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplianceAssessment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "assessment_type",
                    models.CharField(
                        choices=[
                            ("self_assessment", "Self Assessment"),
                            ("internal_audit", "Internal Audit"),
                            ("external_audit", "External Audit"),
                            ("penetration_test", "Penetration Test"),
                            ("vulnerability_assessment", "Vulnerability Assessment"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                ("scope_description", models.TextField(blank=True)),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ComplianceControl",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("control_id", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "control_type",
                    models.CharField(
                        choices=[
                            ("preventive", "Preventive"),
                            ("detective", "Detective"),
                            ("corrective", "Corrective"),
                            ("administrative", "Administrative"),
                            ("technical", "Technical"),
                            ("physical", "Physical"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "criticality",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("implementation_guidance", models.TextField(blank=True)),
                ("testing_procedures", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["framework", "control_id"],
            },
        ),
        migrations.CreateModel(
            name="ComplianceEvidence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "evidence_type",
                    models.CharField(
                        choices=[
                            ("document", "Document"),
                            ("screenshot", "Screenshot"),
                            ("log_file", "Log File"),
                            ("configuration", "Configuration"),
                            ("test_result", "Test Result"),
                            ("interview", "Interview Notes"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("file_path", models.CharField(blank=True, max_length=500)),
                ("file_hash", models.CharField(blank=True, max_length=64)),
                ("collected_at", models.DateTimeField(auto_now_add=True)),
                ("is_valid", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-collected_at"],
            },
        ),
        migrations.CreateModel(
            name="ComplianceException",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("justification", models.TextField()),
                ("compensating_controls", models.TextField(blank=True)),
                ("risk_assessment", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("valid_from", models.DateTimeField()),
                ("valid_until", models.DateTimeField()),
                ("review_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ComplianceFramework",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("version", models.CharField(blank=True, max_length=50)),
                ("authority", models.CharField(blank=True, max_length=100)),
                ("website", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ComplianceResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("compliant", "Compliant"),
                            ("non_compliant", "Non-Compliant"),
                            ("partially_compliant", "Partially Compliant"),
                            ("not_applicable", "Not Applicable"),
                            ("not_tested", "Not Tested"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("findings", models.TextField(blank=True)),
                ("recommendations", models.TextField(blank=True)),
                ("remediation_plan", models.TextField(blank=True)),
                ("tested_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="compliance.complianceassessment",
                    ),
                ),
                (
                    "control",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="compliance.compliancecontrol",
                    ),
                ),
                (
                    "evidence",
                    models.ManyToManyField(
                        blank=True,
                        related_name="results",
                        to="compliance.complianceevidence",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ComplianceMetrics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("metric_date", models.DateTimeField()),
                ("total_controls", models.PositiveIntegerField()),
                ("compliant_controls", models.PositiveIntegerField()),
                ("non_compliant_controls", models.PositiveIntegerField()),
                ("partially_compliant_controls", models.PositiveIntegerField()),
                ("not_applicable_controls", models.PositiveIntegerField()),
                ("not_tested_controls", models.PositiveIntegerField()),
                (
                    "compliance_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("high_risk_findings", models.PositiveIntegerField(default=0)),
                ("medium_risk_findings", models.PositiveIntegerField(default=0)),
                ("low_risk_findings", models.PositiveIntegerField(default=0)),
                ("open_exceptions", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="compliance.complianceassessment",
                    ),
                ),
                (
                    "framework",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="compliance.complianceframework",
                    ),
                ),
            ],
            options={
                "ordering": ["-metric_date"],
            },
        ),
        migrations.AddIndex(
            model_name="complianceframework",
            index=models.Index(fields=["name"], name="compliance__name_c5c23b_idx"),
        ),
        migrations.AddIndex(
            model_name="complianceframework",
            index=models.Index(
                fields=["is_active"], name="compliance__is_acti_8b196c_idx"
            ),
        ),
        migrations.AddField(
            model_name="complianceexception",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_exceptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="complianceexception",
            name="assets",
            field=models.ManyToManyField(
                blank=True, related_name="compliance_exceptions", to="assets.asset"
            ),
        ),
        migrations.AddField(
            model_name="complianceexception",
            name="control",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exceptions",
                to="compliance.compliancecontrol",
            ),
        ),
        migrations.AddField(
            model_name="complianceexception",
            name="requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requested_exceptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="complianceevidence",
            name="assessment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evidence",
                to="compliance.complianceassessment",
            ),
        ),
        migrations.AddField(
            model_name="complianceevidence",
            name="collected_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="complianceevidence",
            name="control",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evidence",
                to="compliance.compliancecontrol",
            ),
        ),
        migrations.AddField(
            model_name="compliancecontrol",
            name="framework",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="controls",
                to="compliance.complianceframework",
            ),
        ),
        migrations.AddField(
            model_name="compliancecontrol",
            name="related_controls",
            field=models.ManyToManyField(blank=True, to="compliance.compliancecontrol"),
        ),
        migrations.AddField(
            model_name="complianceassessment",
            name="assessor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assessments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="complianceassessment",
            name="assets",
            field=models.ManyToManyField(
                blank=True, related_name="compliance_assessments", to="assets.asset"
            ),
        ),
        migrations.AddField(
            model_name="complianceassessment",
            name="framework",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessments",
                to="compliance.complianceframework",
            ),
        ),
        migrations.AddIndex(
            model_name="complianceresult",
            index=models.Index(
                fields=["assessment", "control"], name="compliance__assessm_9090dc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="complianceresult",
            index=models.Index(fields=["status"], name="compliance__status_bc3ee2_idx"),
        ),
        migrations.AddIndex(
            model_name="complianceresult",
            index=models.Index(
                fields=["risk_level"], name="compliance__risk_le_b90a94_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="complianceresult",
            index=models.Index(
                fields=["tested_at"], name="compliance__tested__2adb27_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="complianceresult",
            unique_together={("assessment", "control")},
        ),
        migrations.AddIndex(
            model_name="compliancemetrics",
            index=models.Index(
                fields=["framework", "metric_date"],
                name="compliance__framewo_b9f982_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="compliancemetrics",
            index=models.Index(
                fields=["assessment", "metric_date"],
                name="compliance__assessm_745e38_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="complianceexception",
            index=models.Index(
                fields=["control"], name="compliance__control_8e66ff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="complianceexception",
            index=models.Index(fields=["status"], name="compliance__status_e08305_idx"),
        ),
        migrations.AddIndex(
            model_name="complianceexception",
            index=models.Index(
                fields=["valid_until"], name="compliance__valid_u_907bb1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="complianceexception",
            index=models.Index(
                fields=["review_date"], name="compliance__review__eb695c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="complianceevidence",
            index=models.Index(
                fields=["assessment", "control"], name="compliance__assessm_b3a1ec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="complianceevidence",
            index=models.Index(
                fields=["evidence_type"], name="compliance__evidenc_e9bb0e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="complianceevidence",
            index=models.Index(
                fields=["collected_at"], name="compliance__collect_c676f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="compliancecontrol",
            index=models.Index(
                fields=["framework", "control_id"],
                name="compliance__framewo_093213_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="compliancecontrol",
            index=models.Index(
                fields=["control_type"], name="compliance__control_4872ee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="compliancecontrol",
            index=models.Index(
                fields=["criticality"], name="compliance__critica_047906_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="compliancecontrol",
            unique_together={("framework", "control_id")},
        ),
        migrations.AddIndex(
            model_name="complianceassessment",
            index=models.Index(
                fields=["framework"], name="compliance__framewo_421c06_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="complianceassessment",
            index=models.Index(fields=["status"], name="compliance__status_6f2275_idx"),
        ),
        migrations.AddIndex(
            model_name="complianceassessment",
            index=models.Index(
                fields=["assessment_type"], name="compliance__assessm_c196a0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="complianceassessment",
            index=models.Index(
                fields=["due_date"], name="compliance__due_dat_a34a2a_idx"
            ),
        ),
    ]
