# Generated by Django 5.2.17 on 2026-10-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="complianceassessment",
            name="team_id",
            field=models.UUIDField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="complianceexception",
            name="team_id",
            field=models.UUIDField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="complianceframework",
            name="team_id",
            field=models.UUIDField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="compliancemetrics",
            name="team_id",
            field=models.UUIDField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="complianceframework",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="complianceframework",
            unique_together={("team_id", "name")},
        ),
    ]
