# Generated by Django 4.2.30 on 2026-06-17 00:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("vulnerability_summary", "Vulnerability Summary"),
                            ("asset_inventory", "Asset Inventory"),
                            ("compliance_status", "Compliance Status"),
                            ("risk_assessment", "Risk Assessment"),
                            ("remediation_progress", "Remediation Progress"),
                            ("executive_dashboard", "Executive Dashboard"),
                            ("technical_details", "Technical Details"),
                            ("trend_analysis", "Trend Analysis"),
                            ("custom", "Custom Report"),
                        ],
                        max_length=30,
                    ),
                ),
                ("template_content", models.TextField()),
                (
                    "default_format",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("html", "HTML"),
                            ("json", "JSON"),
                            ("csv", "CSV"),
                            ("xlsx", "Excel"),
                        ],
                        default="pdf",
                        max_length=10,
                    ),
                ),
                ("filters_schema", models.JSONField(blank=True, default=dict)),
                ("parameters_schema", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("is_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ReportSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("once", "Once"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("filters", models.JSONField(blank=True, default=dict)),
                ("recipients", models.JSONField(blank=True, default=list)),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("html", "HTML"),
                            ("json", "JSON"),
                            ("csv", "CSV"),
                            ("xlsx", "Excel"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("disabled", "Disabled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("next_run", models.DateTimeField()),
                ("last_run", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="reporting.reporttemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["next_run"],
            },
        ),
        migrations.CreateModel(
            name="ReportMetrics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("metric_date", models.DateTimeField()),
                ("generation_count", models.PositiveIntegerField(default=0)),
                ("avg_generation_time", models.DurationField(blank=True, null=True)),
                (
                    "success_rate",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("total_file_size", models.PositiveBigIntegerField(default=0)),
                ("unique_users", models.PositiveIntegerField(default=0)),
                ("download_count", models.PositiveIntegerField(default=0)),
                ("error_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="reporting.reporttemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-metric_date"],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("generating", "Generating"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="generating",
                        max_length=20,
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("html", "HTML"),
                            ("json", "JSON"),
                            ("csv", "CSV"),
                            ("xlsx", "Excel"),
                        ],
                        max_length=10,
                    ),
                ),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("filters", models.JSONField(blank=True, default=dict)),
                ("file_path", models.CharField(blank=True, max_length=500)),
                ("file_size", models.PositiveIntegerField(blank=True, null=True)),
                ("file_hash", models.CharField(blank=True, max_length=64)),
                ("generation_time", models.DurationField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to="reporting.reportschedule",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="reporting.reporttemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="Dashboard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "dashboard_type",
                    models.CharField(
                        choices=[
                            ("executive", "Executive"),
                            ("security", "Security"),
                            ("compliance", "Compliance"),
                            ("operational", "Operational"),
                            ("custom", "Custom"),
                        ],
                        max_length=20,
                    ),
                ),
                ("layout_config", models.JSONField(default=dict)),
                ("widgets_config", models.JSONField(default=list)),
                ("filters_config", models.JSONField(blank=True, default=dict)),
                ("refresh_interval", models.PositiveIntegerField(default=300)),
                ("is_active", models.BooleanField(default=True)),
                ("is_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_dashboards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shared_with",
                    models.ManyToManyField(
                        blank=True,
                        related_name="shared_dashboards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AlertRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("data_source", models.CharField(max_length=100)),
                (
                    "condition_type",
                    models.CharField(
                        choices=[
                            ("threshold", "Threshold"),
                            ("change", "Change"),
                            ("trend", "Trend"),
                            ("anomaly", "Anomaly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("condition_config", models.JSONField(default=dict)),
                ("threshold_value", models.FloatField(blank=True, null=True)),
                (
                    "operator",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("gt", "Greater Than"),
                            ("lt", "Less Than"),
                            ("eq", "Equal To"),
                            ("gte", "Greater Than or Equal"),
                            ("lte", "Less Than or Equal"),
                            ("ne", "Not Equal"),
                        ],
                        max_length=10,
                    ),
                ),
                ("notification_config", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("last_triggered", models.DateTimeField(blank=True, null=True)),
                ("trigger_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Widget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "widget_type",
                    models.CharField(
                        choices=[
                            ("chart", "Chart"),
                            ("table", "Table"),
                            ("metric", "Metric"),
                            ("gauge", "Gauge"),
                            ("progress", "Progress Bar"),
                            ("list", "List"),
                            ("map", "Map"),
                            ("custom", "Custom"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "chart_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("line", "Line Chart"),
                            ("bar", "Bar Chart"),
                            ("pie", "Pie Chart"),
                            ("donut", "Donut Chart"),
                            ("area", "Area Chart"),
                            ("scatter", "Scatter Plot"),
                            ("heatmap", "Heatmap"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("data_source", models.CharField(max_length=100)),
                ("query_config", models.JSONField(default=dict)),
                ("display_config", models.JSONField(default=dict)),
                ("refresh_interval", models.PositiveIntegerField(default=300)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["widget_type"], name="reporting_w_widget__88e296_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="reporting_w_is_acti_ffc8c8_idx"
                    ),
                    models.Index(
                        fields=["data_source"], name="reporting_w_data_so_a915c3_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="reporttemplate",
            index=models.Index(
                fields=["report_type"], name="reporting_r_report__1dd4a1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reporttemplate",
            index=models.Index(
                fields=["is_active"], name="reporting_r_is_acti_bf78fa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reporttemplate",
            index=models.Index(
                fields=["created_by"], name="reporting_r_created_e6fa50_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reportschedule",
            index=models.Index(
                fields=["status", "next_run"], name="reporting_r_status_1283c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reportschedule",
            index=models.Index(
                fields=["template"], name="reporting_r_templat_3f0dd9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reportschedule",
            index=models.Index(
                fields=["created_by"], name="reporting_r_created_293f9e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reportmetrics",
            index=models.Index(
                fields=["template", "metric_date"],
                name="reporting_r_templat_f6e3bb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reportmetrics",
            index=models.Index(
                fields=["metric_date"], name="reporting_r_metric__4b79d3_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="reportmetrics",
            unique_together={("template", "metric_date")},
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["template"], name="reporting_r_templat_0c4af9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(fields=["status"], name="reporting_r_status_b3f463_idx"),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["generated_at"], name="reporting_r_generat_9f5407_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["expires_at"], name="reporting_r_expires_3c9d9e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dashboard",
            index=models.Index(
                fields=["dashboard_type"], name="reporting_d_dashboa_98bad4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dashboard",
            index=models.Index(
                fields=["is_active"], name="reporting_d_is_acti_e8e3bc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dashboard",
            index=models.Index(
                fields=["created_by"], name="reporting_d_created_803778_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alertrule",
            index=models.Index(
                fields=["is_active"], name="reporting_a_is_acti_1f4353_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alertrule",
            index=models.Index(
                fields=["condition_type"], name="reporting_a_conditi_3a77bc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alertrule",
            index=models.Index(
                fields=["last_triggered"], name="reporting_a_last_tr_7e6b48_idx"
            ),
        ),
    ]
