# Generated by Django 5.2.17 on 2026-10-02 18:23

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="alertrule",
            name="firing_since",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="alertrule",
            name="last_evaluated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="alertrule",
            name="last_notified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="alertrule",
            name="last_value",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="alertrule",
            name="state",
            field=models.CharField(
                choices=[("ok", "OK"), ("firing", "Firing")],
                default="ok",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="AlertNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("firing", "Started firing"),
                            ("repeat", "Still firing"),
                            ("resolved", "Resolved"),
                        ],
                        max_length=10,
                    ),
                ),
                ("value", models.FloatField()),
                ("threshold_value", models.FloatField(blank=True, null=True)),
                ("operator", models.CharField(blank=True, max_length=10)),
                ("recipients", models.JSONField(blank=True, default=list)),
                ("delivered", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="reporting.alertrule",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["rule", "created_at"],
                        name="reporting_a_rule_id_6bf75e_idx",
                    )
                ],
            },
        ),
    ]
