# Generated by Django 5.2.17 on 2026-10-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0003_team_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="alertnotification",
            name="failure_reason",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
