# Generated by Django 4.2.30 on 2026-06-17 00:24

import apps.vulnerabilities.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vulnerability",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField()),
                ("cve_id", models.CharField(blank=True, db_index=True, max_length=20)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("info", "Info"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "cvss_v3_score",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(10.0),
                        ],
                    ),
                ),
                ("cvss_v3_vector", models.CharField(blank=True, max_length=200)),
                (
                    "risk_score",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(10.0),
                        ],
                    ),
                ),
                (
                    "threat_level",
                    models.CharField(
                        choices=[
                            ("imminent", "Imminent"),
                            ("active", "Active"),
                            ("emerging", "Emerging"),
                            ("possible", "Possible"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "exploitability_score",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(10.0),
                        ],
                    ),
                ),
                (
                    "business_impact_score",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(10.0),
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In Progress"),
                            ("resolved", "Resolved"),
                            ("accepted", "Accepted"),
                            ("false_positive", "False Positive"),
                            ("duplicate", "Duplicate"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("p1", "P1 - Emergency"),
                            ("p2", "P2 - High"),
                            ("p3", "P3 - Medium"),
                            ("p4", "P4 - Low"),
                        ],
                        default="p3",
                        max_length=20,
                    ),
                ),
                ("port", models.PositiveIntegerField(blank=True, null=True)),
                ("protocol", models.CharField(blank=True, max_length=10)),
                ("service", models.CharField(blank=True, max_length=100)),
                (
                    "plugin_id",
                    models.CharField(
                        blank=True, help_text="Scanner plugin ID", max_length=100
                    ),
                ),
                (
                    "evidence",
                    models.TextField(
                        blank=True, help_text="Evidence or proof of concept"
                    ),
                ),
                (
                    "solution",
                    models.TextField(blank=True, help_text="Recommended solution"),
                ),
                (
                    "references",
                    models.JSONField(
                        blank=True, default=list, help_text="List of reference URLs"
                    ),
                ),
                (
                    "scanner",
                    models.CharField(
                        blank=True,
                        help_text="Scanner that found this vulnerability",
                        max_length=100,
                    ),
                ),
                (
                    "scan_id",
                    models.CharField(
                        blank=True, help_text="Scan ID for tracking", max_length=100
                    ),
                ),
                (
                    "assignee_group",
                    models.CharField(
                        blank=True, help_text="Team or group assigned", max_length=100
                    ),
                ),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                (
                    "sla_hours",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="SLA in hours based on priority",
                        null=True,
                    ),
                ),
                ("first_discovered", models.DateTimeField(auto_now_add=True)),
                ("last_detected", models.DateTimeField(auto_now=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional vulnerability metadata",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vulnerabilities",
                        to="assets.asset",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_vulnerabilities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_vulnerabilities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-risk_score", "-cvss_v3_score", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VulnerabilityTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cve_id", models.CharField(blank=True, max_length=20, unique=True)),
                ("title", models.CharField(max_length=500)),
                ("description_template", models.TextField()),
                ("solution_template", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("info", "Info"),
                        ],
                        max_length=20,
                    ),
                ),
                ("cvss_v3_score", models.FloatField(blank=True, null=True)),
                ("cvss_v3_vector", models.CharField(blank=True, max_length=200)),
                ("category", models.CharField(blank=True, max_length=100)),
                (
                    "cwe_id",
                    models.CharField(
                        blank=True,
                        help_text="Common Weakness Enumeration ID",
                        max_length=20,
                    ),
                ),
                ("owasp_category", models.CharField(blank=True, max_length=100)),
                (
                    "default_priority",
                    models.CharField(
                        choices=[
                            ("p1", "P1 - Emergency"),
                            ("p2", "P2 - High"),
                            ("p3", "P3 - Medium"),
                            ("p4", "P4 - Low"),
                        ],
                        default="p3",
                        max_length=10,
                    ),
                ),
                ("default_sla_hours", models.PositiveIntegerField(default=168)),
                ("references", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["cve_id", "title"],
            },
        ),
        migrations.CreateModel(
            name="VulnerabilityNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                (
                    "note_type",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("analysis", "Analysis"),
                            ("remediation", "Remediation"),
                            ("escalation", "Escalation"),
                            ("approval", "Approval"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vulnerability",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="vulnerabilities.vulnerability",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VulnerabilityHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=50)),
                ("old_value", models.TextField(blank=True)),
                ("new_value", models.TextField(blank=True)),
                ("change_reason", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vulnerability",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="vulnerabilities.vulnerability",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="VulnerabilityAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="vulnerability_attachments/%Y/%m/%d/",
                        validators=[
                            apps.vulnerabilities.models.validate_attachment_file
                        ],
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("file_size", models.PositiveIntegerField()),
                ("content_type", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "attachment_type",
                    models.CharField(
                        choices=[
                            ("screenshot", "Screenshot"),
                            ("report", "Report"),
                            ("log", "Log File"),
                            ("evidence", "Evidence"),
                            ("patch", "Patch File"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vulnerability",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="vulnerabilities.vulnerability",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="VulnerabilityAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exploit_available", models.BooleanField(default=False)),
                ("exploit_public", models.BooleanField(default=False)),
                ("exploit_weaponized", models.BooleanField(default=False)),
                ("active_campaigns", models.BooleanField(default=False)),
                (
                    "threat_actor_interest",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "network_exposure",
                    models.CharField(
                        choices=[
                            ("internet", "Internet Facing"),
                            ("internal", "Internal Network"),
                            ("isolated", "Isolated/DMZ"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "data_sensitivity",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("internal", "Internal"),
                            ("confidential", "Confidential"),
                            ("restricted", "Restricted"),
                        ],
                        default="internal",
                        max_length=20,
                    ),
                ),
                ("waf_protection", models.BooleanField(default=False)),
                ("network_segmentation", models.BooleanField(default=False)),
                ("monitoring_coverage", models.BooleanField(default=False)),
                ("access_restrictions", models.BooleanField(default=False)),
                (
                    "availability_impact",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("none", "None"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "confidentiality_impact",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("none", "None"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "integrity_impact",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("none", "None"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("assessed_at", models.DateTimeField(auto_now=True)),
                ("assessment_notes", models.TextField(blank=True)),
                ("threat_intelligence_score", models.FloatField(default=0.0)),
                ("environmental_score", models.FloatField(default=0.0)),
                ("business_impact_score", models.FloatField(default=0.0)),
                (
                    "assessed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vulnerability",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment",
                        to="vulnerabilities.vulnerability",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="vulnerability",
            index=models.Index(fields=["cve_id"], name="vulnerabili_cve_id_4cecd1_idx"),
        ),
        migrations.AddIndex(
            model_name="vulnerability",
            index=models.Index(
                fields=["severity"], name="vulnerabili_severit_6939ec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vulnerability",
            index=models.Index(fields=["status"], name="vulnerabili_status_828c5c_idx"),
        ),
        migrations.AddIndex(
            model_name="vulnerability",
            index=models.Index(
                fields=["priority"], name="vulnerabili_priorit_f2eca5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vulnerability",
            index=models.Index(
                fields=["risk_score"], name="vulnerabili_risk_sc_2ae063_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vulnerability",
            index=models.Index(
                fields=["due_date"], name="vulnerabili_due_dat_5be10c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vulnerability",
            index=models.Index(
                fields=["asset", "status"], name="vulnerabili_asset_i_8bf58b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="vulnerability",
            unique_together={("asset", "cve_id", "port")},
        ),
    ]
