# Generated by Django 5.2.17 on 2026-10-03 14:51

import apps.vulnerabilities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vulnerabilitytemplate",
            name="team_id",
            field=models.UUIDField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="vulnerabilityattachment",
            name="file",
            field=models.FileField(
                upload_to=apps.vulnerabilities.models.attachment_upload_to,
                validators=[apps.vulnerabilities.models.validate_attachment_file],
            ),
        ),
        migrations.AlterField(
            model_name="vulnerabilitytemplate",
            name="cve_id",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name="vulnerabilitytemplate",
            unique_together={("team_id", "cve_id")},
        ),
    ]
