# Generated by Django 5.2.17 on 2026-10-05 11:00

import django.utils.timezone
from django.db import migrations, models
from django.db.models import F


def last_seen_is_first_seen(apps, schema_editor):
    """Existing rows were last seen when they were first seen, as far as
    guardian knows (#676).

    AddField gives them the time of the migration, which would make every
    row count for a whole TEAM_MEMBERSHIP_MAX_AGE from the upgrade: the
    members who left a team before guardian was told of removals would be
    its users again for a month. ``first_seen`` is the one moment guardian
    has evidence for. A member who still uses guardian is refreshed by their
    next request; one who left is not.
    """
    TeamMembership = apps.get_model("core", "TeamMembership")
    TeamMembership.objects.update(last_seen=F("first_seen"))


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_team_membership_and_tasks"),
    ]

    operations = [
        migrations.AddField(
            model_name="teammembership",
            name="last_seen",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.RunPython(last_seen_is_first_seen, migrations.RunPython.noop),
    ]
