# Generated by Django 5.2.17 on 2026-10-05 17:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_team_membership_last_seen"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamMembershipRevocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(db_index=True, max_length=150)),
                ("team_id", models.UUIDField(blank=True, db_index=True, null=True)),
                (
                    "revoked_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
            ],
        ),
    ]
