# Generated by Django 4.2.30 on 2026-06-17 00:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalSystem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "system_type",
                    models.CharField(
                        choices=[
                            ("ticketing", "Ticketing System"),
                            ("siem", "SIEM/SOAR"),
                            ("notification", "Notification System"),
                            ("cmdb", "Configuration Management"),
                            ("monitoring", "Monitoring System"),
                            ("threat_intel", "Threat Intelligence"),
                            ("scanning", "Vulnerability Scanner"),
                            ("compliance", "Compliance System"),
                            ("orchestration", "Security Orchestration"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "vendor",
                    models.CharField(
                        blank=True, help_text="System vendor/provider", max_length=100
                    ),
                ),
                ("version", models.CharField(blank=True, max_length=50)),
                (
                    "base_url",
                    models.URLField(validators=[django.core.validators.URLValidator()]),
                ),
                (
                    "api_endpoint",
                    models.CharField(
                        blank=True, help_text="API endpoint path", max_length=200
                    ),
                ),
                (
                    "auth_type",
                    models.CharField(
                        choices=[
                            ("api_key", "API Key"),
                            ("oauth2", "OAuth 2.0"),
                            ("basic", "Basic Auth"),
                            ("bearer", "Bearer Token"),
                            ("custom", "Custom Auth"),
                        ],
                        default="api_key",
                        max_length=20,
                    ),
                ),
                (
                    "auth_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Authentication configuration",
                    ),
                ),
                ("verify_ssl", models.BooleanField(default=True)),
                ("timeout_seconds", models.PositiveIntegerField(default=30)),
                ("retry_attempts", models.PositiveIntegerField(default=3)),
                (
                    "rate_limit_per_minute",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("error", "Error"),
                            ("testing", "Testing"),
                            ("maintenance", "Maintenance"),
                        ],
                        default="inactive",
                        max_length=20,
                    ),
                ),
                ("last_health_check", models.DateTimeField(blank=True, null=True)),
                ("last_sync", models.DateTimeField(blank=True, null=True)),
                (
                    "health_check_interval",
                    models.PositiveIntegerField(
                        default=300, help_text="Health check interval in seconds"
                    ),
                ),
                ("supports_bidirectional_sync", models.BooleanField(default=False)),
                ("supports_webhooks", models.BooleanField(default=False)),
                ("supports_real_time", models.BooleanField(default=False)),
                (
                    "field_mappings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Field mapping configuration",
                    ),
                ),
                (
                    "sync_filters",
                    models.JSONField(
                        blank=True, default=dict, help_text="Data sync filters"
                    ),
                ),
                ("total_requests", models.PositiveIntegerField(default=0)),
                ("successful_requests", models.PositiveIntegerField(default=0)),
                ("failed_requests", models.PositiveIntegerField(default=0)),
                ("avg_response_time_ms", models.FloatField(default=0.0)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="IntegrationMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "guardian_entity",
                    models.CharField(
                        choices=[
                            ("vulnerability", "Vulnerability"),
                            ("asset", "Asset"),
                            ("remediation", "Remediation"),
                            ("scan", "Scan"),
                            ("user", "User"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "external_entity",
                    models.CharField(
                        help_text="External system entity name", max_length=100
                    ),
                ),
                (
                    "field_mappings",
                    models.JSONField(
                        default=dict,
                        help_text="Guardian field -> External field mappings",
                    ),
                ),
                (
                    "value_transformations",
                    models.JSONField(
                        blank=True, default=dict, help_text="Value transformation rules"
                    ),
                ),
                (
                    "sync_direction",
                    models.CharField(
                        choices=[
                            ("guardian_to_external", "Guardian → External"),
                            ("external_to_guardian", "External → Guardian"),
                            ("bidirectional", "Bidirectional"),
                        ],
                        default="guardian_to_external",
                        max_length=20,
                    ),
                ),
                ("auto_sync", models.BooleanField(default=True)),
                (
                    "sync_frequency",
                    models.PositiveIntegerField(
                        default=300, help_text="Sync frequency in seconds"
                    ),
                ),
                (
                    "sync_conditions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Conditions for syncing records",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mappings",
                        to="integrations.externalsystem",
                    ),
                ),
            ],
            options={
                "ordering": ["system", "guardian_entity"],
                "unique_together": {("system", "guardian_entity", "external_entity")},
            },
        ),
        migrations.CreateModel(
            name="WebhookEndpoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "endpoint_url",
                    models.CharField(
                        help_text="Webhook endpoint path", max_length=500, unique=True
                    ),
                ),
                (
                    "secret_token",
                    models.CharField(
                        blank=True,
                        help_text="Webhook verification token",
                        max_length=200,
                    ),
                ),
                (
                    "event_types",
                    models.JSONField(
                        default=list, help_text="List of event types to trigger webhook"
                    ),
                ),
                (
                    "filters",
                    models.JSONField(
                        blank=True, default=dict, help_text="Event filters"
                    ),
                ),
                ("verify_signature", models.BooleanField(default=True)),
                (
                    "allowed_ips",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Allowed source IP addresses",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_triggered", models.DateTimeField(blank=True, null=True)),
                ("total_requests", models.PositiveIntegerField(default=0)),
                ("successful_requests", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhooks",
                        to="integrations.externalsystem",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="NotificationChannel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "channel_type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("slack", "Slack"),
                            ("teams", "Microsoft Teams"),
                            ("webhook", "Generic Webhook"),
                            ("sms", "SMS"),
                            ("push", "Push Notification"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        default=dict, help_text="Channel-specific configuration"
                    ),
                ),
                (
                    "event_types",
                    models.JSONField(default=list, help_text="Subscribed event types"),
                ),
                (
                    "severity_filter",
                    models.JSONField(
                        blank=True, default=list, help_text="Severity levels to notify"
                    ),
                ),
                (
                    "recipients",
                    models.JSONField(default=list, help_text="Notification recipients"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_notification", models.DateTimeField(blank=True, null=True)),
                ("total_notifications", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ApiUsageMetrics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                (
                    "hour",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Hour of day (0-23) for hourly metrics",
                        null=True,
                    ),
                ),
                ("total_requests", models.PositiveIntegerField(default=0)),
                ("successful_requests", models.PositiveIntegerField(default=0)),
                ("failed_requests", models.PositiveIntegerField(default=0)),
                ("avg_response_time_ms", models.FloatField(default=0.0)),
                ("min_response_time_ms", models.PositiveIntegerField(default=0)),
                ("max_response_time_ms", models.PositiveIntegerField(default=0)),
                ("bytes_sent", models.PositiveBigIntegerField(default=0)),
                ("bytes_received", models.PositiveBigIntegerField(default=0)),
                ("auth_errors", models.PositiveIntegerField(default=0)),
                ("rate_limit_errors", models.PositiveIntegerField(default=0)),
                ("timeout_errors", models.PositiveIntegerField(default=0)),
                ("server_errors", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_metrics",
                        to="integrations.externalsystem",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-hour"],
            },
        ),
        migrations.CreateModel(
            name="SyncRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "guardian_record_id",
                    models.UUIDField(help_text="Guardian record UUID"),
                ),
                (
                    "external_record_id",
                    models.CharField(
                        help_text="External system record ID", max_length=200
                    ),
                ),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("conflict", "Conflict"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "last_sync_direction",
                    models.CharField(
                        choices=[
                            ("guardian_to_external", "Guardian → External"),
                            ("external_to_guardian", "External → Guardian"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_sync_at", models.DateTimeField(auto_now=True)),
                ("next_sync_at", models.DateTimeField(blank=True, null=True)),
                ("sync_attempts", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("conflict_details", models.JSONField(blank=True, default=dict)),
                ("guardian_last_modified", models.DateTimeField(blank=True, null=True)),
                ("external_last_modified", models.DateTimeField(blank=True, null=True)),
                ("sync_metadata", models.JSONField(blank=True, default=dict)),
                (
                    "mapping",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_records",
                        to="integrations.integrationmapping",
                    ),
                ),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_records",
                        to="integrations.externalsystem",
                    ),
                ),
            ],
            options={
                "ordering": ["-last_sync_at"],
                "indexes": [
                    models.Index(
                        fields=["system", "sync_status"],
                        name="integration_system__268e88_idx",
                    ),
                    models.Index(
                        fields=["guardian_record_id"],
                        name="integration_guardia_61fdfc_idx",
                    ),
                    models.Index(
                        fields=["external_record_id"],
                        name="integration_externa_252160_idx",
                    ),
                    models.Index(
                        fields=["next_sync_at"], name="integration_next_sy_37f850_idx"
                    ),
                ],
                "unique_together": {("system", "guardian_record_id", "mapping")},
            },
        ),
        migrations.CreateModel(
            name="IntegrationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("sync", "Data Sync"),
                            ("webhook", "Webhook"),
                            ("health_check", "Health Check"),
                            ("auth", "Authentication"),
                            ("api_call", "API Call"),
                            ("error", "Error"),
                            ("config_change", "Configuration Change"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("debug", "Debug"),
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("critical", "Critical"),
                        ],
                        default="info",
                        max_length=10,
                    ),
                ),
                ("message", models.TextField()),
                ("details", models.JSONField(blank=True, default=dict)),
                (
                    "record_id",
                    models.UUIDField(
                        blank=True, help_text="Related Guardian record ID", null=True
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        help_text="Related external record ID",
                        max_length=200,
                    ),
                ),
                ("request_data", models.JSONField(blank=True, default=dict)),
                ("response_data", models.JSONField(blank=True, default=dict)),
                (
                    "response_time_ms",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="integrations.externalsystem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["system", "operation"],
                        name="integration_system__ddd452_idx",
                    ),
                    models.Index(fields=["level"], name="integration_level_a81e3a_idx"),
                    models.Index(
                        fields=["-created_at"], name="integration_created_131d44_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="externalsystem",
            index=models.Index(
                fields=["system_type"], name="integration_system__5e0878_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="externalsystem",
            index=models.Index(fields=["status"], name="integration_status_324848_idx"),
        ),
        migrations.AddIndex(
            model_name="externalsystem",
            index=models.Index(
                fields=["last_health_check"], name="integration_last_he_f0e1e6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apiusagemetrics",
            index=models.Index(
                fields=["system", "date"], name="integration_system__ff5757_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apiusagemetrics",
            index=models.Index(
                fields=["date", "hour"], name="integration_date_bfeec5_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="apiusagemetrics",
            unique_together={("system", "date", "hour")},
        ),
    ]
