# Generated by Django 5.2.17 on 2026-10-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="externalsystem",
            name="team_id",
            field=models.UUIDField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="notificationchannel",
            name="team_id",
            field=models.UUIDField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
    ]
