# Generated by Django 5.2.17 on 2026-10-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0002_team_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webhookendpoint",
            name="endpoint_url",
            field=models.CharField(
                db_index=True, help_text="Webhook endpoint path", max_length=500
            ),
        ),
        migrations.AddConstraint(
            model_name="webhookendpoint",
            constraint=models.UniqueConstraint(
                fields=("system", "endpoint_url"), name="webhook_path_unique_per_system"
            ),
        ),
    ]
