# Generated by Django 4.2.30 on 2026-06-17 00:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vulnerabilities", "0001_initial"),
        ("assets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Scanner",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "scanner_type",
                    models.CharField(
                        choices=[
                            ("nessus", "Nessus"),
                            ("qualys", "Qualys"),
                            ("openvas", "OpenVAS"),
                            ("rapid7", "Rapid7 InsightVM"),
                            ("custom", "Custom Scanner"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "base_url",
                    models.URLField(validators=[django.core.validators.URLValidator()]),
                ),
                (
                    "api_key",
                    models.CharField(
                        blank=True, help_text="API key or token", max_length=500
                    ),
                ),
                ("username", models.CharField(blank=True, max_length=100)),
                (
                    "password",
                    models.CharField(
                        blank=True, help_text="Encrypted password", max_length=100
                    ),
                ),
                ("verify_ssl", models.BooleanField(default=True)),
                ("timeout_seconds", models.PositiveIntegerField(default=30)),
                ("max_concurrent_scans", models.PositiveIntegerField(default=5)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("maintenance", "Maintenance"),
                            ("error", "Error"),
                        ],
                        default="inactive",
                        max_length=20,
                    ),
                ),
                ("last_health_check", models.DateTimeField(blank=True, null=True)),
                (
                    "health_check_interval",
                    models.PositiveIntegerField(
                        default=300, help_text="Health check interval in seconds"
                    ),
                ),
                ("supports_authenticated_scans", models.BooleanField(default=False)),
                ("supports_compliance_scans", models.BooleanField(default=False)),
                ("supports_agent_scans", models.BooleanField(default=False)),
                ("total_scans_completed", models.PositiveIntegerField(default=0)),
                ("total_vulnerabilities_found", models.PositiveIntegerField(default=0)),
                ("avg_scan_duration_minutes", models.FloatField(default=0.0)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ScanProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "scan_template_id",
                    models.CharField(
                        blank=True,
                        help_text="Scanner-specific template ID",
                        max_length=100,
                    ),
                ),
                (
                    "scan_policy_id",
                    models.CharField(
                        blank=True,
                        help_text="Scanner-specific policy ID",
                        max_length=100,
                    ),
                ),
                ("enable_safe_checks", models.BooleanField(default=True)),
                ("enable_web_app_tests", models.BooleanField(default=False)),
                ("enable_compliance_checks", models.BooleanField(default=False)),
                (
                    "port_range",
                    models.CharField(
                        default="1-65535",
                        help_text="Port range to scan",
                        max_length=100,
                    ),
                ),
                (
                    "exclude_ports",
                    models.CharField(
                        blank=True, help_text="Ports to exclude", max_length=200
                    ),
                ),
                (
                    "scan_speed",
                    models.CharField(
                        choices=[
                            ("slow", "Slow"),
                            ("normal", "Normal"),
                            ("fast", "Fast"),
                            ("aggressive", "Aggressive"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                ("max_scan_duration_hours", models.PositiveIntegerField(default=24)),
                ("advanced_settings", models.JSONField(blank=True, default=dict)),
                ("times_used", models.PositiveIntegerField(default=0)),
                ("avg_scan_time_minutes", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scanner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profiles",
                        to="scanners.scanner",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("scanner", "name")},
            },
        ),
        migrations.CreateModel(
            name="ScanSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("target_ranges", models.JSONField(blank=True, default=list)),
                (
                    "cron_expression",
                    models.CharField(
                        help_text="Cron expression for scheduling", max_length=100
                    ),
                ),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("next_run", models.DateTimeField(blank=True, null=True)),
                ("last_run", models.DateTimeField(blank=True, null=True)),
                ("total_runs", models.PositiveIntegerField(default=0)),
                ("successful_runs", models.PositiveIntegerField(default=0)),
                ("failed_runs", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scanners.scanprofile",
                    ),
                ),
                (
                    "scanner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scanners.scanner",
                    ),
                ),
                (
                    "target_assets",
                    models.ManyToManyField(blank=True, to="assets.asset"),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Scan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "target_ranges",
                    models.JSONField(
                        blank=True, default=list, help_text="IP ranges and hostnames"
                    ),
                ),
                ("scheduled_start", models.DateTimeField(blank=True, null=True)),
                (
                    "recurrence_pattern",
                    models.CharField(
                        blank=True, help_text="Cron-like schedule", max_length=100
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("paused", "Paused"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "scanner_scan_id",
                    models.CharField(
                        blank=True, help_text="Scanner's native scan ID", max_length=100
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("total_hosts_scanned", models.PositiveIntegerField(default=0)),
                ("total_vulnerabilities_found", models.PositiveIntegerField(default=0)),
                ("critical_count", models.PositiveIntegerField(default=0)),
                ("high_count", models.PositiveIntegerField(default=0)),
                ("medium_count", models.PositiveIntegerField(default=0)),
                ("low_count", models.PositiveIntegerField(default=0)),
                ("info_count", models.PositiveIntegerField(default=0)),
                ("progress_percentage", models.FloatField(default=0.0)),
                ("current_host", models.CharField(blank=True, max_length=200)),
                ("error_message", models.TextField(blank=True)),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("max_retries", models.PositiveIntegerField(default=3)),
                ("scan_settings", models.JSONField(blank=True, default=dict)),
                ("scan_metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="scanners.scanprofile",
                    ),
                ),
                (
                    "scanner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scans",
                        to="scanners.scanner",
                    ),
                ),
                (
                    "target_assets",
                    models.ManyToManyField(related_name="scans", to="assets.asset"),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScanResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("plugin_id", models.CharField(max_length=100)),
                ("plugin_name", models.CharField(max_length=500)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("info", "Info"),
                        ],
                        max_length=20,
                    ),
                ),
                ("cve_ids", models.JSONField(blank=True, default=list)),
                ("cvss_base_score", models.FloatField(blank=True, null=True)),
                ("cvss_vector", models.CharField(blank=True, max_length=200)),
                ("host", models.CharField(max_length=200)),
                ("port", models.PositiveIntegerField(blank=True, null=True)),
                ("protocol", models.CharField(blank=True, max_length=10)),
                ("service", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField()),
                ("solution", models.TextField(blank=True)),
                (
                    "proof",
                    models.TextField(
                        blank=True, help_text="Proof of concept or evidence"
                    ),
                ),
                ("references", models.JSONField(blank=True, default=list)),
                ("processed", models.BooleanField(default=False)),
                ("vulnerability_created", models.BooleanField(default=False)),
                (
                    "raw_data",
                    models.JSONField(
                        blank=True, default=dict, help_text="Raw scanner output"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assets.asset",
                    ),
                ),
                (
                    "scan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="scanners.scan",
                    ),
                ),
                (
                    "vulnerability",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="vulnerabilities.vulnerability",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["scan", "severity"],
                        name="scanners_sc_scan_id_f1d1e5_idx",
                    ),
                    models.Index(
                        fields=["host", "port"], name="scanners_sc_host_95d337_idx"
                    ),
                    models.Index(
                        fields=["processed"], name="scanners_sc_process_6a91e6_idx"
                    ),
                    models.Index(
                        fields=["vulnerability_created"],
                        name="scanners_sc_vulnera_059096_idx",
                    ),
                ],
                "unique_together": {("scan", "host", "port", "plugin_id")},
            },
        ),
        migrations.AddIndex(
            model_name="scanner",
            index=models.Index(
                fields=["scanner_type"], name="scanners_sc_scanner_eb4778_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scanner",
            index=models.Index(fields=["status"], name="scanners_sc_status_8a189e_idx"),
        ),
        migrations.AddIndex(
            model_name="scanner",
            index=models.Index(
                fields=["last_health_check"], name="scanners_sc_last_he_06277f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scan",
            index=models.Index(fields=["status"], name="scanners_sc_status_34b9f0_idx"),
        ),
        migrations.AddIndex(
            model_name="scan",
            index=models.Index(
                fields=["scheduled_start"], name="scanners_sc_schedul_b0afc8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scan",
            index=models.Index(
                fields=["scanner", "status"], name="scanners_sc_scanner_fc04c5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scan",
            index=models.Index(
                fields=["-created_at"], name="scanners_sc_created_55890e_idx"
            ),
        ),
    ]
