# Generated by Django 4.2.30 on 2026-06-17 00:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vulnerabilities", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RemediationTicket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField()),
                (
                    "system",
                    models.CharField(
                        choices=[
                            ("jira", "Jira"),
                            ("servicenow", "ServiceNow"),
                            ("github", "GitHub Issues"),
                            ("gitlab", "GitLab Issues"),
                            ("azure_devops", "Azure DevOps"),
                            ("custom", "Custom System"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "external_ticket_id",
                    models.CharField(
                        help_text="Ticket ID in external system", max_length=100
                    ),
                ),
                (
                    "external_url",
                    models.URLField(
                        blank=True, validators=[django.core.validators.URLValidator()]
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("emergency", "Emergency (P0)"),
                            ("high", "High (P1)"),
                            ("medium", "Medium (P2)"),
                            ("low", "Low (P3)"),
                            ("planned", "Planned (P4)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("assigned", "Assigned"),
                            ("in_progress", "In Progress"),
                            ("testing", "Testing"),
                            ("completed", "Completed"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                            ("deferred", "Deferred"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "assigned_team",
                    models.CharField(
                        blank=True, help_text="External team assignment", max_length=100
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "system_metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="System-specific metadata"
                    ),
                ),
                (
                    "sync_enabled",
                    models.BooleanField(
                        default=True, help_text="Enable bidirectional sync"
                    ),
                ),
                ("last_sync", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RemediationWorkflow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                (
                    "remediation_type",
                    models.CharField(
                        choices=[
                            ("patch", "Software Patch"),
                            ("configuration", "Configuration Change"),
                            ("workaround", "Workaround Implementation"),
                            ("upgrade", "System Upgrade"),
                            ("replacement", "Component Replacement"),
                            ("mitigation", "Risk Mitigation"),
                            ("acceptance", "Risk Acceptance"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("assigned", "Assigned"),
                            ("in_progress", "In Progress"),
                            ("testing", "Testing"),
                            ("completed", "Completed"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                            ("deferred", "Deferred"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("emergency", "Emergency (P0)"),
                            ("high", "High (P1)"),
                            ("medium", "Medium (P2)"),
                            ("low", "Low (P3)"),
                            ("planned", "Planned (P4)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("assigned_team", models.CharField(blank=True, max_length=100)),
                ("estimated_effort_hours", models.FloatField(blank=True, null=True)),
                ("actual_effort_hours", models.FloatField(blank=True, null=True)),
                ("planned_start_date", models.DateTimeField(blank=True, null=True)),
                ("actual_start_date", models.DateTimeField(blank=True, null=True)),
                (
                    "planned_completion_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("actual_completion_date", models.DateTimeField(blank=True, null=True)),
                (
                    "remediation_steps",
                    models.JSONField(
                        blank=True, default=list, help_text="List of remediation steps"
                    ),
                ),
                (
                    "rollback_plan",
                    models.TextField(
                        blank=True, help_text="Rollback procedures if needed"
                    ),
                ),
                (
                    "testing_plan",
                    models.TextField(
                        blank=True, help_text="Testing and validation plan"
                    ),
                ),
                ("business_justification", models.TextField(blank=True)),
                ("maintenance_window_required", models.BooleanField(default=False)),
                (
                    "downtime_expected_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("affected_systems", models.JSONField(blank=True, default=list)),
                ("prerequisite_tasks", models.TextField(blank=True)),
                (
                    "progress_percentage",
                    models.FloatField(
                        default=0.0, help_text="0-100 completion percentage"
                    ),
                ),
                ("current_step", models.CharField(blank=True, max_length=200)),
                (
                    "implementation_risk",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("risk_mitigation_notes", models.TextField(blank=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approving_remediations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_remediations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "blocking_issues",
                    models.ManyToManyField(
                        blank=True,
                        related_name="blocked_by",
                        to="remediation.remediationworkflow",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_remediations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="remediation.remediationticket",
                    ),
                ),
                (
                    "vulnerability",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="remediation",
                        to="vulnerabilities.vulnerability",
                    ),
                ),
            ],
            options={
                "ordering": ["-priority", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RemediationTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(help_text="Remediation category", max_length=100),
                ),
                (
                    "remediation_type",
                    models.CharField(
                        choices=[
                            ("patch", "Software Patch"),
                            ("configuration", "Configuration Change"),
                            ("workaround", "Workaround Implementation"),
                            ("upgrade", "System Upgrade"),
                            ("replacement", "Component Replacement"),
                            ("mitigation", "Risk Mitigation"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "default_priority",
                    models.CharField(
                        choices=[
                            ("emergency", "Emergency (P0)"),
                            ("high", "High (P1)"),
                            ("medium", "Medium (P2)"),
                            ("low", "Low (P3)"),
                            ("planned", "Planned (P4)"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("estimated_effort_hours", models.FloatField(blank=True, null=True)),
                (
                    "step_templates",
                    models.JSONField(
                        default=list, help_text="Template steps for the workflow"
                    ),
                ),
                ("rollback_template", models.TextField(blank=True)),
                ("testing_template", models.TextField(blank=True)),
                ("usage_count", models.PositiveIntegerField(default=0)),
                (
                    "success_rate",
                    models.FloatField(default=0.0, help_text="Success rate percentage"),
                ),
                (
                    "vulnerability_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Applicable vulnerability types",
                    ),
                ),
                (
                    "asset_types",
                    models.JSONField(
                        blank=True, default=list, help_text="Applicable asset types"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="RemediationStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "order",
                    models.PositiveIntegerField(help_text="Step execution order"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "estimated_duration_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "actual_duration_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "instructions",
                    models.TextField(help_text="Detailed step instructions"),
                ),
                (
                    "validation_criteria",
                    models.TextField(
                        blank=True, help_text="How to validate step completion"
                    ),
                ),
                (
                    "automation_script",
                    models.TextField(
                        blank=True, help_text="Optional automation script"
                    ),
                ),
                ("execution_notes", models.TextField(blank=True)),
                ("validation_results", models.TextField(blank=True)),
                (
                    "attachments",
                    models.JSONField(
                        blank=True, default=list, help_text="File attachments"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="remediation.remediationworkflow",
                    ),
                ),
            ],
            options={
                "ordering": ["workflow", "order"],
            },
        ),
        migrations.CreateModel(
            name="RemediationMetrics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("remediations_created", models.PositiveIntegerField(default=0)),
                ("remediations_completed", models.PositiveIntegerField(default=0)),
                ("remediations_overdue", models.PositiveIntegerField(default=0)),
                ("avg_completion_time_hours", models.FloatField(default=0.0)),
                (
                    "sla_compliance_rate",
                    models.FloatField(default=0.0, help_text="Percentage"),
                ),
                (
                    "first_time_fix_rate",
                    models.FloatField(default=0.0, help_text="Percentage"),
                ),
                ("emergency_completed", models.PositiveIntegerField(default=0)),
                ("high_completed", models.PositiveIntegerField(default=0)),
                ("medium_completed", models.PositiveIntegerField(default=0)),
                ("low_completed", models.PositiveIntegerField(default=0)),
                (
                    "team_metrics",
                    models.JSONField(
                        blank=True, default=dict, help_text="Per-team performance data"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("date", "period_type")},
            },
        ),
        migrations.CreateModel(
            name="RemediationComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "comment_type",
                    models.CharField(
                        choices=[
                            ("general", "General Comment"),
                            ("status_update", "Status Update"),
                            ("issue", "Issue/Problem"),
                            ("resolution", "Resolution"),
                            ("approval", "Approval"),
                            ("rejection", "Rejection"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                (
                    "is_internal",
                    models.BooleanField(
                        default=False,
                        help_text="Internal comment, not synced to external systems",
                    ),
                ),
                ("attachments", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="remediation.remediationworkflow",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="remediationworkflow",
            index=models.Index(fields=["status"], name="remediation_status_75834c_idx"),
        ),
        migrations.AddIndex(
            model_name="remediationworkflow",
            index=models.Index(
                fields=["priority"], name="remediation_priorit_748fb9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="remediationworkflow",
            index=models.Index(
                fields=["assigned_to"], name="remediation_assigne_74147b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="remediationworkflow",
            index=models.Index(
                fields=["planned_completion_date"],
                name="remediation_planned_1cb3da_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="remediationworkflow",
            index=models.Index(
                fields=["vulnerability"], name="remediation_vulnera_80abbe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="remediationticket",
            index=models.Index(
                fields=["system", "external_ticket_id"],
                name="remediation_system_f2f365_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="remediationticket",
            index=models.Index(fields=["status"], name="remediation_status_f0f7f6_idx"),
        ),
        migrations.AddIndex(
            model_name="remediationticket",
            index=models.Index(
                fields=["priority"], name="remediation_priorit_af0d39_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="remediationticket",
            index=models.Index(
                fields=["due_date"], name="remediation_due_dat_e43fda_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="remediationticket",
            unique_together={("system", "external_ticket_id")},
        ),
        migrations.AlterUniqueTogether(
            name="remediationstep",
            unique_together={("workflow", "order")},
        ),
    ]
