# Generated by Django 5.2.17 on 2026-10-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("remediation", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="remediationticket",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="remediationtemplate",
            name="team_id",
            field=models.UUIDField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="remediationticket",
            name="team_id",
            field=models.UUIDField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AlterUniqueTogether(
            name="remediationticket",
            unique_together={("team_id", "system", "external_ticket_id")},
        ),
    ]
