# Generated by Django 4.2.30 on 2026-06-17 00:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("server", "Server"),
                            ("workstation", "Workstation"),
                            ("network_device", "Network Device"),
                            ("mobile_device", "Mobile Device"),
                            ("iot_device", "IoT Device"),
                            ("cloud_instance", "Cloud Instance"),
                            ("container", "Container"),
                            ("application", "Application"),
                            ("database", "Database"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("decommissioned", "Decommissioned"),
                            ("maintenance", "Maintenance"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("hostname", models.CharField(blank=True, max_length=255)),
                (
                    "fqdn",
                    models.CharField(blank=True, max_length=255, verbose_name="FQDN"),
                ),
                ("mac_address", models.CharField(blank=True, max_length=17)),
                (
                    "criticality",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of tags for categorization",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional asset metadata"
                    ),
                ),
                (
                    "discovered_by",
                    models.CharField(
                        blank=True,
                        help_text="Discovery method or scanner",
                        max_length=100,
                    ),
                ),
                ("first_discovered", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="BusinessFunction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "criticality_weight",
                    models.FloatField(default=1.0, help_text="Criticality multiplier"),
                ),
                ("compliance_required", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Environment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "risk_weight",
                    models.FloatField(
                        default=1.0, help_text="Risk multiplier for this environment"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AssetGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "auto_assignment_rules",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Rules for automatic asset assignment",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assets",
                    models.ManyToManyField(
                        blank=True, related_name="groups", to="assets.asset"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AssetDiscoveryRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "discovery_type",
                    models.CharField(
                        choices=[
                            ("network_scan", "Network Scan"),
                            ("cloud_api", "Cloud API"),
                            ("cmdb_import", "CMDB Import"),
                            ("agent_report", "Agent Report"),
                            ("dns_zone", "DNS Zone Transfer"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "target_specification",
                    models.JSONField(
                        help_text="Target networks, APIs, or other discovery targets"
                    ),
                ),
                (
                    "schedule",
                    models.CharField(
                        help_text="Cron schedule for discovery", max_length=100
                    ),
                ),
                (
                    "default_criticality",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("classification_rules", models.JSONField(blank=True, default=dict)),
                ("enabled", models.BooleanField(default=True)),
                ("last_run", models.DateTimeField(blank=True, null=True)),
                ("next_run", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "default_environment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="assets.environment",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="asset",
            name="business_function",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="assets.businessfunction",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_assets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="environment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="assets.environment",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_assets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="technical_contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_assets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="AssetSoftware",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("version", models.CharField(blank=True, max_length=100)),
                ("vendor", models.CharField(blank=True, max_length=255)),
                ("installation_path", models.CharField(blank=True, max_length=500)),
                ("is_critical", models.BooleanField(default=False)),
                ("is_licensed", models.BooleanField(default=True)),
                ("license_expiry", models.DateField(blank=True, null=True)),
                ("discovered_by", models.CharField(blank=True, max_length=100)),
                ("first_discovered", models.DateTimeField(auto_now_add=True)),
                ("last_verified", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="software",
                        to="assets.asset",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "version"],
                "unique_together": {("asset", "name", "version")},
            },
        ),
        migrations.CreateModel(
            name="AssetPort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("port_number", models.PositiveIntegerField()),
                (
                    "protocol",
                    models.CharField(
                        choices=[("tcp", "TCP"), ("udp", "UDP")], max_length=10
                    ),
                ),
                ("service", models.CharField(blank=True, max_length=100)),
                ("service_version", models.CharField(blank=True, max_length=100)),
                ("banner", models.TextField(blank=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("closed", "Closed"),
                            ("filtered", "Filtered"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("discovered_by", models.CharField(blank=True, max_length=100)),
                ("first_discovered", models.DateTimeField(auto_now_add=True)),
                ("last_verified", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ports",
                        to="assets.asset",
                    ),
                ),
            ],
            options={
                "ordering": ["port_number"],
                "unique_together": {("asset", "port_number", "protocol")},
            },
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["ip_address"], name="assets_asse_ip_addr_c30137_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["hostname"], name="assets_asse_hostnam_606d95_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["asset_type"], name="assets_asse_asset_t_529092_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["criticality"], name="assets_asse_critica_a56ae2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(fields=["status"], name="assets_asse_status_347ce9_idx"),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["last_seen"], name="assets_asse_last_se_79d094_idx"
            ),
        ),
    ]
