# Generated by Django 5.2.17 on 2026-10-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="team_id",
            field=models.UUIDField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="assetdiscoveryrule",
            name="team_id",
            field=models.UUIDField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="assetgroup",
            name="team_id",
            field=models.UUIDField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="businessfunction",
            name="team_id",
            field=models.UUIDField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="environment",
            name="team_id",
            field=models.UUIDField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="assetdiscoveryrule",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="assetgroup",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="businessfunction",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="environment",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name="assetdiscoveryrule",
            unique_together={("team_id", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="assetgroup",
            unique_together={("team_id", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="businessfunction",
            unique_together={("team_id", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="environment",
            unique_together={("team_id", "name")},
        ),
    ]
