"""Every variable ``.env.example`` offers is one the stack reads (#665).

The template listed ``REQUIRE_MFA=false``, ``SESSION_TIMEOUT=3600`` and three
more under "Security Settings", and no Compose file passed any of them to a
container: an operator who wrote ``REQUIRE_MFA=true`` had required nothing.
``GUARDIAN_DB_PASSWORD``, ``NEXTAUTH_SECRET`` and ``GRAFANA_ADMIN_PASSWORD``
were there too, the last two generated by ``generate_secrets.py`` and checked
by ``validate_secrets.py``, for a dashboard with no NextAuth and a stack with
no Grafana.

The root ``.env`` reaches a container only through a root Compose file, which
names the variable (``${NAME}``). So:

* a variable of the template, set or commented out, is interpolated by one of
  the three root Compose files;
* a secret ``generate_secrets.py`` writes, or ``validate_secrets.py`` asks
  for, is a variable of the template.

``generate_secrets.py`` is read, never run.
"""

import ast
import importlib.util
import re
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]
TEMPLATE = ROOT / ".env.example"
COMPOSE_FILES = (
    "docker-compose.yml",
    "docker-compose.prod.yml",
    "docker-compose.dev.yml",
)
GENERATOR = ROOT / "scripts" / "generate_secrets.py"
VALIDATOR = ROOT / "scripts" / "validate_secrets.py"

ASSIGNED = re.compile(r"^#? ?([A-Z][A-Z0-9_]*)=", re.M)


def template_variables(text=None):
    """The names the template assigns, on a line of its own or commented out."""
    if text is None:
        text = TEMPLATE.read_text(encoding="utf-8")
    return set(ASSIGNED.findall(text))


def interpolated(text=None):
    """The names the root Compose files take from the environment."""
    if text is None:
        text = "\n".join(
            (ROOT / name).read_text(encoding="utf-8") for name in COMPOSE_FILES
        )
    settings = "\n".join(
        line for line in text.splitlines() if not line.lstrip().startswith("#")
    )
    return set(re.findall(r"\$\{([A-Z][A-Z0-9_]*)", settings))


def string_keys(path, name):
    """The string keys or items of the dict or list assigned to ``name``."""
    tree = ast.parse(path.read_text(encoding="utf-8"))
    for node in ast.walk(tree):
        if not isinstance(node, ast.Assign):
            continue
        if getattr(node.targets[0], "id", None) != name:
            continue
        items = node.value.keys if isinstance(node.value, ast.Dict) else node.value.elts
        return [item.value for item in items]
    raise AssertionError(f"{path.name} assigns no {name}")


# --- the check works -----------------------------------------------------------


def test_the_template_is_read():
    names = template_variables()

    assert {"POSTGRES_PASSWORD", "ENVIRONMENT", "REDIS_PASSWORD"} <= names
    # A commented-out example is offered as much as a set one.
    assert "GUARDIAN_RATE_LIMIT_USER" in names
    assert "#" not in "".join(names)


def test_a_variable_no_compose_file_names_is_found():
    template = "KEPT=1\n# OFFERED=2\nREQUIRE_MFA=false\n# prose with A=b in it\n"
    compose = "environment:\n  - KEPT=${KEPT}\n  - X=${OFFERED:-}\n  # ${REQUIRE_MFA}\n"

    assert template_variables(template) == {"KEPT", "OFFERED", "REQUIRE_MFA"}
    assert template_variables(template) - interpolated(compose) == {"REQUIRE_MFA"}


def test_the_generator_and_the_validator_are_read():
    assert "JWT_SECRET_KEY" in string_keys(GENERATOR, "secrets_map")
    assert "JWT_SECRET_KEY" in string_keys(VALIDATOR, "REQUIRED_SECRETS")
    assert "GUARDIAN_CONTACTS_SECRET" in string_keys(VALIDATOR, "OPTIONAL_SECRETS")


# --- the tree -------------------------------------------------------------------


def test_every_variable_of_the_template_reaches_a_container():
    assert sorted(template_variables() - interpolated()) == []


@pytest.mark.parametrize(
    "path, name",
    [
        (GENERATOR, "secrets_map"),
        (VALIDATOR, "REQUIRED_SECRETS"),
        (VALIDATOR, "OPTIONAL_SECRETS"),
    ],
)
def test_a_generated_or_validated_secret_is_in_the_template(path, name):
    offered = template_variables()

    assert sorted(set(string_keys(path, name)) - offered) == []


def test_every_secret_the_validator_requires_is_generated():
    generated = set(string_keys(GENERATOR, "secrets_map"))

    assert sorted(set(string_keys(VALIDATOR, "REQUIRED_SECRETS")) - generated) == []


@pytest.mark.parametrize(
    "name",
    [
        "NEXTAUTH_SECRET",
        "GRAFANA_ADMIN_PASSWORD",
        "GUARDIAN_DB_PASSWORD",
        "REQUIRE_MFA",
        "REQUIRE_EMAIL_VERIFICATION",
        "SESSION_TIMEOUT",
        "MAX_LOGIN_ATTEMPTS",
        "LOCKOUT_DURATION",
        "STRIPE_SECRET_KEY",
    ],
)
def test_what_nothing_read_is_gone(name):
    assert name not in template_variables()
    assert name not in interpolated()
    for path in (GENERATOR, VALIDATOR, ROOT / "scripts" / "rotate_secrets.sh"):
        assert name not in path.read_text(encoding="utf-8"), path.name


# --- the services' own templates ------------------------------------------------
#
# open-security-guardian/.env.example offered 119 variables, 48 of which
# guardian never read (JWT_SECRET_KEY, RATE_LIMIT_ENABLED, AWS_ACCESS_KEY_ID,
# BACKUP_ENCRYPTION_KEY...), and thirty more that its settings read into
# dictionaries no code used. The data service's offered 67 for the 17 it
# reads. A variable of a service's template is one the service's code reads,
# by the rule of test_compose_variables_are_read.py, or one a Compose file in
# the service's directory takes from the environment.


def _load(name):
    path = Path(__file__).with_name(f"{name}.py")
    spec = importlib.util.spec_from_file_location(f"wildbox_665_{name}", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def service_templates():
    return sorted(ROOT.glob("open-security-*/.env.*"))


def unread_in(template, is_read):
    directory = template.parent
    own_compose = "\n".join(
        path.read_text(encoding="utf-8")
        for path in sorted(directory.glob("docker-compose*.yml"))
    )
    return sorted(
        name
        for name in template_variables(template.read_text(encoding="utf-8"))
        if not is_read(name, directory) and name not in interpolated(own_compose)
    )


def test_the_service_templates_are_found():
    names = {str(path.relative_to(ROOT)) for path in service_templates()}

    assert {
        "open-security-guardian/.env.example",
        "open-security-data/.env.example",
        "open-security-tools/.env.example",
        "open-security-identity/.env.example",
        "open-security-agents/.env.example",
    } <= names


@pytest.mark.parametrize(
    "template", service_templates(), ids=lambda path: path.parent.name
)
def test_every_variable_of_a_service_template_is_read(template):
    compose_variables = _load("test_compose_variables_are_read")

    def is_read(name, directory):
        return name in compose_variables.READ_BY_THE_RUNTIME or (
            compose_variables.is_read(name, directory)
        )

    assert unread_in(template, is_read) == []


def test_a_variable_the_service_does_not_read_is_found(tmp_path):
    service = tmp_path / "open-security-example"
    service.mkdir()
    (service / "config.py").write_text(
        'import os\nLEVEL = os.getenv("LOG_LEVEL", "INFO")\n', encoding="utf-8"
    )
    (service / "docker-compose.yml").write_text(
        "services:\n  db:\n    environment:\n      - P=${POSTGRES_PASSWORD}\n",
        encoding="utf-8",
    )
    template = service / ".env.example"
    template.write_text(
        "LOG_LEVEL=INFO\nPOSTGRES_PASSWORD=\n# JWT_EXPIRATION_HOURS=24\n",
        encoding="utf-8",
    )
    compose_variables = _load("test_compose_variables_are_read")

    assert unread_in(template, compose_variables.is_read) == ["JWT_EXPIRATION_HOURS"]


def test_every_variable_of_the_tests_template_is_read_by_a_test():
    """tests/.env.example is loaded by the integration tests (tests/.env)."""
    sources = "\n".join(
        path.read_text(encoding="utf-8", errors="ignore")
        for pattern in ("*.py", "*.sh")
        for path in (ROOT / "tests").rglob(pattern)
        if "scripts" not in path.relative_to(ROOT / "tests").parts
    )
    names = template_variables((ROOT / "tests" / ".env.example").read_text("utf-8"))

    assert {"TEST_ADMIN_EMAIL", "GATEWAY_SERVICE_URL"} <= names
    assert (
        sorted(name for name in names if not re.search(rf"\b{name}\b", sources)) == []
    )
